# Generated by Django 5.2.7 on 2025-10-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_remove_ingredients_comedogenic_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
