# Generated by Django 5.2.7 on 2025-10-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_ingredients_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='category',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
