# Generated by Django 5.2.7 on 2025-11-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_migrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('Cleanser', 'Cleanser'), ('Toner', 'Toner'), ('Serum', 'Serum'), ('Moisturizer', 'Moisturizer'), ('Sunscreen', 'Sunscreen'), ('Other', 'Other')], max_length=50),
        ),
    ]
