# Generated by Django 5.2.7 on 2025-11-28 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_brand_productsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubmission',
            name='ingredients',
        ),
    ]
