# Generated by Django 5.2.7 on 2025-11-28 21:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_alter_ingredients_category'),
        ('products', '0006_remove_productsubmission_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubmission',
            name='ingredients',
            field=models.ManyToManyField(to='ingredients.ingredients'),
        ),
        migrations.AddField(
            model_name='productsubmission',
            name='raw_ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
        migrations.AddField(
            model_name='productsubmission',
            name='raw_ingredients_text',
            field=models.TextField(null=True),
        ),
    ]
