# Generated by Django 5.2.7 on 2025-11-28 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productsubmission_ingredients_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubmission',
            name='raw_ingredients_text',
        ),
    ]
