# Generated by Django 5.2.7 on 2025-12-05 16:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_productsubmission_raw_ingredients_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='raw_ingredients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
    ]
