# Generated by Django 5.2.7 on 2025-12-31 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_products_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='custom_made',
            field=models.BooleanField(default=False),
        ),
    ]
