# Generated by Django 5.2.7 on 2026-01-03 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_alter_ingredients_category'),
        ('products', '0011_products_custom_made'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='products',
            constraint=models.UniqueConstraint(condition=models.Q(('custom_made', True)), fields=('name', 'created_by'), name='unique_custom_product_per_user'),
        ),
    ]
