# Generated by Django 5.2.7 on 2025-10-21 02:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_avoid_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists'}, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
