# Generated by Django 5.2.7 on 2025-11-13 00:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skin_type',
            field=models.CharField(choices=[('Dry', 'Dry'), ('Normal', 'Normal'), ('Oily', 'Oily'), ('Acne', 'Acne'), ('Sensitive', 'Sensitive'), ('Combination', 'Combination')], error_messages={'blank': 'A skin type is required', 'invalid_choice': 'Please select a valid skin type from the list'}, max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'blank': 'A username is required', 'unique': 'A user with that username already exists'}, max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
