# Generated by Django 5.2.7 on 2025-12-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_products_created_by'),
        ('users', '0005_alter_user_skin_type_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='products',
            field=models.ManyToManyField(related_name='users', to='products.products'),
        ),
    ]
