# Generated by Django 5.2.7 on 2025-12-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_products_created_by'),
        ('users', '0006_user_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='products',
        ),
        migrations.AddField(
            model_name='user',
            name='day_products',
            field=models.ManyToManyField(related_name='day_products', to='products.products'),
        ),
        migrations.AddField(
            model_name='user',
            name='night_products',
            field=models.ManyToManyField(related_name='night_products', to='products.products'),
        ),
    ]
