# Generated by Django 5.2.7 on 2026-01-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_products_custom_made'),
        ('users', '0007_remove_user_products_user_day_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='day_products',
            field=models.ManyToManyField(related_name='users_with_day_products', to='products.products'),
        ),
        migrations.AlterField(
            model_name='user',
            name='night_products',
            field=models.ManyToManyField(related_name='users_with_night_products', to='products.products'),
        ),
    ]
